### ISSUE TITLE
Determine about how long we want the game to be (30 min)

### ISSUE THREAD

**Issue by straker** [straker/js13k-2021#3]
Since a lot of players won't play for long, something on the shorter side is probably best. Maybe somewhere between 10-30 minutes?

For example, [T-Minus 30](https://store.steampowered.com/app/1371750/TMinus_30/) is a city builder played in exactly 30 minutes and that feels like a good amount of time.

**Comment by dllndv** [comment]
That sounds like a good amount of time

**Comment by straker** [comment]
30 minutes it is.
