### ISSUE TITLE
Determine art style

### ISSUE THREAD

**Issue by straker** [straker/js13k-2021#4]
With not a lot of room we can't get too fancy, but Kenney has a great 1-bit tileset available that we could reduce to the parts we need / modify that should fit within the size quite nicely. It has a lot of things in it already, and even has spaceships

https://kenney.nl/assets/bit-pack

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/2433219/131437909-ed182193-56ac-492d-86c1-74d4a944991e.png">

**Comment by dllndv** [comment]
those look good! I can see plenty of options there for the look of conveyor belts, even a couple we could use for mining rigs.

**Comment by straker** [comment]
Send me a screenshot of the ones you think would work for mining machines and ill get the code setup to demo it off. I was thinking of using the big  carets in the 2nd to bottom row for the belts, and the bottom walls for the walls (more sci-fi rather than medieval)

**Comment by dllndv** [comment]
I was thinking this for the drill machine: 
![image](https://user-images.githubusercontent.com/1750196/131726379-140f6314-17f7-46a8-8ba8-b817e2b2eee7.png)

 and then these could be used as the drill bits, maybe the one on the left for the first one, and the one on the right could be an upgrade that mines faster?
![image](https://user-images.githubusercontent.com/1750196/131726529-c043fdac-7138-4316-80fb-e38c56b3972e.png)

**Comment by dllndv** [comment]
That rounded part looks like it would fit in the nook at the top of the machine, and we could animate it by flipping the image back and forth, that zigzag in the middle might look like it's a spinning shaft. (complete noob when it comes to animations, not sure if that works)

**Comment by straker** [comment]
<img width="268" alt="image" src="https://user-images.githubusercontent.com/2433219/131754928-51dc5419-a341-409d-a1ab-0f4cae185b37.png">

**Comment by straker** [comment]
Playing around with # of rooms and mine location

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/2433219/131790705-decad54d-c091-4b0d-b5b0-31fbd0a2b626.png">

**Comment by dllndv** [comment]
That looks awesome! What are some parts that I can work on? I should have all day tomorrow free, and no plans for the day off on Monday. We could do a video call, or even meet somewhere in person, if you want.

**Comment by straker** [comment]
I take half days on Friday (today) so I can look into organizing everything and creating some tickets.

**Comment by straker** [comment]
Going to close this ticket as done
